### ISSUE TITLE
Not passing the date value to the model

### ISSUE THREAD

**Issue by baki250** [rorymadden/angular-date-dropdowns#4]
Hi
Can you check if when dates are selected that its not passing the final date to the ng-model value

Thanks

**Comment by Tim1977** [comment]
You may also need to change as below

 $scope.checkDate = function () {
            var date = rmDateUtils.checkDate($scope.dateFields);
          if (date) {

///CHANGES HERE
              $scope.dateFields = { day: date.getDate(), month: date.getMonth(), year: date.getFullYear() }

              $scope.model = date;

    
          }
        };
