### ISSUE TITLE
Just wonder if anyone has got this directive to work. 

### ISSUE THREAD

**Issue by Tim1977** [rorymadden/angular-date-dropdowns#9]
It does n't seem to pass a new Date to the Model. 
Is there a working code sample anywhere? Thanks a lot

**Comment by Tim1977** [comment]
This is what I changed to get it working.....rightly or wrongly



 $scope.checkDate = function () {
            var date = rmDateUtils.checkDate($scope.dateFields);
          if (date) {

///CHANGES HERE
              $scope.dateFields = { day: date.getDate(), month: date.getMonth(), year: date.getFullYear() }

              $scope.model = date;

    
          }
        };

**Comment by gareththackeray** [comment]
Tim - I was just about to ask the same question.  Glad someone else had the same query!

**Comment by vikrama** [comment]
Damn. Seeing this msg only now. Wasted like 2 hours lol. Have submitted a PR. Thx Tim.
